---
# Common tasks for all Linux machines.

- name: "logrotate: Enable compress"
  lineinfile:
    dest: /etc/logrotate.d/0-local
    create: yes
    regexp: "compress$"
    line: "compress"

- name: "logrotate: Enable dateext"
  lineinfile:
    dest: /etc/logrotate.d/0-local
    create: yes
    regexp: "dateext$"
    line: "dateext"

- name: Disable IPv6
  template:
    src: local-disable-ipv6.conf
    dest: /etc/sysctl.d/
  when: "'ipv6_disabled' in group_names"

- name: Setup ssh with sftp and chroot
  copy:
    src: local-sftp-chroot.conf
    dest: /etc/ssh/sshd_config.d/
  notify: Reload sshd
  when: "'sshd_sftp_chroot' in group_names"

