---
# common tasks for all UCS machines

- name: Install default packages
  # The default mailer should be nullmailer, see https://s2.meissner.it/it/projects/mit-doc/wiki/E-Mail_Server
  apt:
    pkg:
    - git
    - patch
    - python
    - sudo
    - vim
  tags: apt

- name: Check postfix relayhost
  become: no
  command: grep "relayhost = {{ smtp_relayhost }}" /etc/postfix/main.cf
  changed_when: no
  register: relayhostset
  failed_when: no
  when: smtp_relayhost is defined

- name: Set postfix relayhost (Univention)
  command: 'ucr set mail/relayhost="{{ smtp_relayhost }}"'
  when: smtp_relayhost is defined and relayhostset.rc == 1

- name: "Copy /etc/sudoers.d/local-mit-dedicated"
  copy:
    src: sudoers.d/local-mit-dedicated-ucs
    dest: /etc/sudoers.d/
    mode: 0440
    validate: 'visudo -cf %s'

