---

# Either use "static: no" or use variables in the include file, otherwise the include will always be used (statically included)
#- name: "Including Debian 7 (Wheezy)"
#  include: "Debian_7.yml"
#  static: no
#  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

# We use ansible_lsb.id instead of ansible_distribution as this adds support for 
# UCS (Univention Corporate Server) which reports ansible_distribution=Debian and
# ansible_lsb.id=Univention

- include_tasks: "{{ ansible_system }}-{{ ansible_lsb.id }}.yml"
  when: ansible_lsb is defined and ansible_lsb.id is defined

# Used by opdns1 (Debian 9 without lsb_release)
- include_tasks: "{{ ansible_system }}-{{ ansible_distribution }}.yml"
  when: ansible_lsb is not defined or ansible_lsb.id is not defined

- include_tasks: "{{ ansible_system }}.yml"

